### ISSUE TITLE
No ability to add attachments to items?

### ISSUE THREAD

**Issue by saadiq** [sprintly/api-docs#7]
The items endpoint POST documentation doesn't mention attachments and attachments endpoint is read only it seems. Am I missing it?

**Comment by nicholasserra** [comment]
@saadiq Looks like we haven't documented the Attachments upload API, apologies. If you do a POST to the attachments api, with files as multipart form data, it should work. The file form data does not need a specific name, we're grabbing any files available in the request. Let me know if you run into any issues with it, as it's probably not commonly used. Thanks!

**Comment by saadiq** [comment]
@nicholasserra The caveat isn't instilling me with a lot of confidence. After failing in code, I decided to try and confirm it works with curl and got a 500. Should this work?

curl -u <EMAIL>:<API_KEY> -F "file=@image.jpg" https://sprint.ly/api/products/<PRODUCT_ID>/items/<ITEM_ID>/attachments.json

Can you confirm? Thanks.

**Comment by nicholasserra** [comment]
Closing this as we've moved conversation to support.
